#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Woof! 🐶'

# ESLint --fix
echo 'Fixing linting problems (if possible). 🔨'
npm run fix

# Prettier
echo 'Checking for formatting problems. 🧪'
npm run check-format || (
    echo "Prettier Check Failed, we'll get 'em next time. Run npm run format, add changes and try commit again. 🙁";
    false;
)

# ESLint
echo 'Lints and checks for formatting problems. 🧪'
npm run lint || (
    echo "ESLint Check Failed, we'll get 'em next time. Make the required changes listed above, add changes and try to commit again. ☹️"
    false;
)

# tsconfig
echo 'Checking for TypeScript errors. 🧪'
npm run check-types || (
    echo "Failed Type check, we'll get 'em next time. Make the required changes listed above, add changes and try to commit again. 🙃"
    false;
)

echo 'Commiting changes. 🥺🥳🚪🏃‍♀️💨🚀🌑'