#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd frontend
echo 'Woof! 🐶'

# ESLint --fix
echo ''
echo 'Fixing linting problems (if possible). 🔨'
npm run fix

# Prettier
echo ''
echo 'Checking for formatting problems. 🧪'
npm run check-format || (
    echo ''
    echo "Prettier Check Failed, we'll get 'em next time. Run npm run format, add changes and try commit again. 🙁";
    false;
)

# ESLint
echo ''
echo 'Checking for linting problems. 🧪'
npm run lint || (
    echo ''
    echo "ESLint Check Failed, we'll get 'em next time. Make the required changes listed above, add changes and try to commit again. ☹️"
    false;
)

# tsconfig
echo ''
echo 'Checking for TypeScript errors. 🧪'
npm run check-types || (
    echo ''
    echo "Failed Type check, we'll get 'em next time. Make the required changes listed above, add changes and try to commit again. 🙃"
    false;
)

echo ''
echo 'The code looks good to me! Commiting changes. 🥺🥳🚪🏃‍♀️💨🚀🌑'
echo ''