"""create tables

Revision ID: 605f8badc215
Revises:
Create Date: 2022-04-14 09:11:52.127774

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '605f8badc215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('country', sa.String(), nullable=True), sa.Column('region', sa.String(), nullable=True),
                    sa.Column('postal_code', sa.String(), nullable=True), sa.Column('street',
                                                                                    sa.String(),
                                                                                    nullable=True),
                    sa.Column('house_number', sa.Integer(), nullable=True), sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_address__id'), 'address', ['_id'], unique=False)
    op.create_index(op.f('ix_address_country'), 'address', ['country'], unique=False)
    op.create_index(op.f('ix_address_house_number'), 'address', ['house_number'], unique=False)
    op.create_index(op.f('ix_address_postal_code'), 'address', ['postal_code'], unique=False)
    op.create_index(op.f('ix_address_region'), 'address', ['region'], unique=False)
    op.create_index(op.f('ix_address_street'), 'address', ['street'], unique=False)
    op.create_table('address_2_customer', sa.Column('customer_number', sa.Integer(), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('customer_number', 'address_id'))
    op.create_table('category', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True), sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_category__id'), 'category', ['_id'], unique=False)
    op.create_index(op.f('ix_category_description'), 'category', ['description'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('department', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True), sa.Column('manager', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_department__id'), 'department', ['_id'], unique=False)
    op.create_index(op.f('ix_department_manager'), 'department', ['manager'], unique=False)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=False)
    op.create_table('employee', sa.Column('employee_number', sa.Integer(), nullable=False),
                    sa.Column('ssn', sa.Integer(), nullable=True), sa.Column('title', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('job_title', sa.String(), nullable=True),
                    sa.Column('department_id', sa.Integer(), nullable=True),
                    sa.Column('warehouse_id', sa.Integer(), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True), sa.Column('email', sa.String(),
                                                                                    nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True), sa.PrimaryKeyConstraint('employee_number'))
    op.create_index(op.f('ix_employee_address_id'), 'employee', ['address_id'], unique=False)
    op.create_index(op.f('ix_employee_department_id'), 'employee', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=False)
    op.create_index(op.f('ix_employee_employee_number'), 'employee', ['employee_number'], unique=False)
    op.create_index(op.f('ix_employee_first_name'), 'employee', ['first_name'], unique=False)
    op.create_index(op.f('ix_employee_job_title'), 'employee', ['job_title'], unique=False)
    op.create_index(op.f('ix_employee_last_name'), 'employee', ['last_name'], unique=False)
    op.create_index(op.f('ix_employee_phone_number'), 'employee', ['phone_number'], unique=False)
    op.create_index(op.f('ix_employee_ssn'), 'employee', ['ssn'], unique=True)
    op.create_index(op.f('ix_employee_title'), 'employee', ['title'], unique=False)
    op.create_index(op.f('ix_employee_warehouse_id'), 'employee', ['warehouse_id'], unique=False)
    op.create_table('invoice', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('OPEN', 'OVERDUE', 'PAID', name='invoicestatus'), nullable=True),
                    sa.Column('issue_date', sa.Date(), nullable=True), sa.Column('due_date', sa.Date(), nullable=True),
                    sa.Column('payment_information_id', sa.Integer(), nullable=True), sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_invoice__id'), 'invoice', ['_id'], unique=False)
    op.create_index(op.f('ix_invoice_due_date'), 'invoice', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoice_issue_date'), 'invoice', ['issue_date'], unique=False)
    op.create_index(op.f('ix_invoice_payment_information_id'), 'invoice', ['payment_information_id'], unique=False)
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.create_table('order', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('customer_number', sa.Integer(), nullable=True),
                    sa.Column('invoice_id', sa.Integer(), nullable=True),
                    sa.Column('status', sa.Enum('OPEN', 'SENT', 'DELIVERED', name='orderstatus'), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('employee_id', sa.Integer(), nullable=True),
                    sa.Column('shipping_services', sa.Integer(), nullable=True), sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_order__id'), 'order', ['_id'], unique=False)
    op.create_index(op.f('ix_order_address_id'), 'order', ['address_id'], unique=False)
    op.create_index(op.f('ix_order_customer_number'), 'order', ['customer_number'], unique=False)
    op.create_index(op.f('ix_order_employee_id'), 'order', ['employee_id'], unique=False)
    op.create_index(op.f('ix_order_invoice_id'), 'order', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_order_shipping_services'), 'order', ['shipping_services'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_table('order_detail', sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('product_item_number', sa.Integer(), nullable=False),
                    sa.Column('price_at_time_of_purchase', sa.Float(), nullable=True),
                    sa.Column('number_of_items', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('order_id', 'product_item_number'))
    op.create_index(op.f('ix_order_detail_number_of_items'), 'order_detail', ['number_of_items'], unique=False)
    op.create_index(op.f('ix_order_detail_order_id'), 'order_detail', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_detail_price_at_time_of_purchase'),
                    'order_detail', ['price_at_time_of_purchase'],
                    unique=False)
    op.create_index(op.f('ix_order_detail_product_item_number'), 'order_detail', ['product_item_number'], unique=False)
    op.create_table('payment_information', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('iban', sa.String(), nullable=True), sa.Column('bic', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_payment_information__id'), 'payment_information', ['_id'], unique=False)
    op.create_index(op.f('ix_payment_information_bic'), 'payment_information', ['bic'], unique=False)
    op.create_index(op.f('ix_payment_information_iban'), 'payment_information', ['iban'], unique=True)
    op.create_table('payment_information_2_customer', sa.Column('customer_number', sa.Integer(), nullable=False),
                    sa.Column('payment_information_id', sa.Integer(), nullable=False),
                    sa.Column('is_default', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('customer_number', 'payment_information_id'))
    op.create_index(op.f('ix_payment_information_2_customer_customer_number'),
                    'payment_information_2_customer', ['customer_number'],
                    unique=False)
    op.create_index(op.f('ix_payment_information_2_customer_payment_information_id'),
                    'payment_information_2_customer', ['payment_information_id'],
                    unique=False)
    op.create_table('postal_code_2_city', sa.Column('postal_code', sa.String(), nullable=False),
                    sa.Column('city', sa.String(), nullable=True), sa.PrimaryKeyConstraint('postal_code'))
    op.create_index(op.f('ix_postal_code_2_city_city'), 'postal_code_2_city', ['city'], unique=False)
    op.create_index(op.f('ix_postal_code_2_city_postal_code'), 'postal_code_2_city', ['postal_code'], unique=False)
    op.create_table('product', sa.Column('item_number', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True), sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('supplier_id', sa.Integer(), nullable=True), sa.PrimaryKeyConstraint('item_number'))
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_item_number'), 'product', ['item_number'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_index(op.f('ix_product_supplier_id'), 'product', ['supplier_id'], unique=False)
    op.create_table('product_2_warehouse', sa.Column('product_item_number', sa.Integer(), nullable=False),
                    sa.Column('warehouse_id', sa.Integer(), nullable=False),
                    sa.Column('number_in_stock', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('product_item_number', 'warehouse_id'))
    op.create_index(op.f('ix_product_2_warehouse_number_in_stock'),
                    'product_2_warehouse', ['number_in_stock'],
                    unique=False)
    op.create_index(op.f('ix_product_2_warehouse_product_item_number'),
                    'product_2_warehouse', ['product_item_number'],
                    unique=False)
    op.create_index(op.f('ix_product_2_warehouse_warehouse_id'), 'product_2_warehouse', ['warehouse_id'], unique=False)
    op.create_table('shipping_service', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True), sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True), sa.Column('phone_number',
                                                                              sa.String(),
                                                                              nullable=True),
                    sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_shipping_service__id'), 'shipping_service', ['_id'], unique=False)
    op.create_index(op.f('ix_shipping_service_address_id'), 'shipping_service', ['address_id'], unique=False)
    op.create_index(op.f('ix_shipping_service_email'), 'shipping_service', ['email'], unique=False)
    op.create_index(op.f('ix_shipping_service_name'), 'shipping_service', ['name'], unique=False)
    op.create_index(op.f('ix_shipping_service_phone_number'), 'shipping_service', ['phone_number'], unique=False)
    op.create_table('supplier', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True), sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True), sa.Column('email',
                                                                                     sa.String(),
                                                                                     nullable=True),
                    sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_supplier__id'), 'supplier', ['_id'], unique=False)
    op.create_index(op.f('ix_supplier_address_id'), 'supplier', ['address_id'], unique=False)
    op.create_index(op.f('ix_supplier_email'), 'supplier', ['email'], unique=False)
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=False)
    op.create_index(op.f('ix_supplier_phone_number'), 'supplier', ['phone_number'], unique=False)
    op.create_table('warehouse', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True), sa.Column('email',
                                                                                     sa.String(),
                                                                                     nullable=True),
                    sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_warehouse__id'), 'warehouse', ['_id'], unique=False)
    op.create_index(op.f('ix_warehouse_address_id'), 'warehouse', ['address_id'], unique=False)
    op.create_index(op.f('ix_warehouse_email'), 'warehouse', ['email'], unique=False)
    op.create_index(op.f('ix_warehouse_phone_number'), 'warehouse', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_phone_number'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_email'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_address_id'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse__id'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_supplier_phone_number'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_email'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_address_id'), table_name='supplier')
    op.drop_index(op.f('ix_supplier__id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_shipping_service_phone_number'), table_name='shipping_service')
    op.drop_index(op.f('ix_shipping_service_name'), table_name='shipping_service')
    op.drop_index(op.f('ix_shipping_service_email'), table_name='shipping_service')
    op.drop_index(op.f('ix_shipping_service_address_id'), table_name='shipping_service')
    op.drop_index(op.f('ix_shipping_service__id'), table_name='shipping_service')
    op.drop_table('shipping_service')
    op.drop_index(op.f('ix_product_2_warehouse_warehouse_id'), table_name='product_2_warehouse')
    op.drop_index(op.f('ix_product_2_warehouse_product_item_number'), table_name='product_2_warehouse')
    op.drop_index(op.f('ix_product_2_warehouse_number_in_stock'), table_name='product_2_warehouse')
    op.drop_table('product_2_warehouse')
    op.drop_index(op.f('ix_product_supplier_id'), table_name='product')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_item_number'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_postal_code_2_city_postal_code'), table_name='postal_code_2_city')
    op.drop_index(op.f('ix_postal_code_2_city_city'), table_name='postal_code_2_city')
    op.drop_table('postal_code_2_city')
    op.drop_index(op.f('ix_payment_information_2_customer_payment_information_id'),
                  table_name='payment_information_2_customer')
    op.drop_index(op.f('ix_payment_information_2_customer_customer_number'),
                  table_name='payment_information_2_customer')
    op.drop_table('payment_information_2_customer')
    op.drop_index(op.f('ix_payment_information_iban'), table_name='payment_information')
    op.drop_index(op.f('ix_payment_information_bic'), table_name='payment_information')
    op.drop_index(op.f('ix_payment_information__id'), table_name='payment_information')
    op.drop_table('payment_information')
    op.drop_index(op.f('ix_order_detail_product_item_number'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_price_at_time_of_purchase'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_order_id'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_number_of_items'), table_name='order_detail')
    op.drop_table('order_detail')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_shipping_services'), table_name='order')
    op.drop_index(op.f('ix_order_invoice_id'), table_name='order')
    op.drop_index(op.f('ix_order_employee_id'), table_name='order')
    op.drop_index(op.f('ix_order_customer_number'), table_name='order')
    op.drop_index(op.f('ix_order_address_id'), table_name='order')
    op.drop_index(op.f('ix_order__id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_payment_information_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_issue_date'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_due_date'), table_name='invoice')
    op.drop_index(op.f('ix_invoice__id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_employee_warehouse_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_title'), table_name='employee')
    op.drop_index(op.f('ix_employee_ssn'), table_name='employee')
    op.drop_index(op.f('ix_employee_phone_number'), table_name='employee')
    op.drop_index(op.f('ix_employee_last_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_job_title'), table_name='employee')
    op.drop_index(op.f('ix_employee_first_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_employee_number'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_index(op.f('ix_employee_department_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_address_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_manager'), table_name='department')
    op.drop_index(op.f('ix_department__id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_description'), table_name='category')
    op.drop_index(op.f('ix_category__id'), table_name='category')
    op.drop_table('category')
    op.drop_table('address_2_customer')
    op.drop_index(op.f('ix_address_street'), table_name='address')
    op.drop_index(op.f('ix_address_region'), table_name='address')
    op.drop_index(op.f('ix_address_postal_code'), table_name='address')
    op.drop_index(op.f('ix_address_house_number'), table_name='address')
    op.drop_index(op.f('ix_address_country'), table_name='address')
    op.drop_index(op.f('ix_address__id'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
