"""apply foreign keys

Revision ID: 99cccb38ce41
Revises: cb5e03d3b31f
Create Date: 2022-04-14 14:47:40.643668

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '99cccb38ce41'
down_revision = 'cb5e03d3b31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'city', ['postal_code'], ['postal_code'])
    op.create_foreign_key(None, 'address_2_customer', 'customer', ['customer_number'], ['customer_number'])
    op.create_foreign_key(None, 'address_2_customer', 'address', ['address_id'], ['_id'])
    op.create_foreign_key(None, 'department', 'employee', ['manager'], ['employee_number'])
    op.create_foreign_key(None, 'employee', 'warehouse', ['warehouse_id'], ['_id'])
    op.create_foreign_key(None, 'employee', 'address', ['address_id'], ['_id'])
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['_id'])
    op.create_foreign_key(None, 'invoice', 'payment_information', ['payment_information_id'], ['_id'])
    op.add_column('order', sa.Column('shipping_service_id', sa.Integer(), nullable=True))
    op.drop_index('ix_order_shipping_services', table_name='order')
    op.create_index(op.f('ix_order_shipping_service_id'), 'order', ['shipping_service_id'], unique=False)
    op.create_foreign_key(None, 'order', 'invoice', ['invoice_id'], ['_id'])
    op.create_foreign_key(None, 'order', 'employee', ['employee_id'], ['employee_number'])
    op.create_foreign_key(None, 'order', 'shipping_service', ['shipping_service_id'], ['_id'])
    op.create_foreign_key(None, 'order', 'customer', ['customer_number'], ['customer_number'])
    op.create_foreign_key(None, 'order', 'address', ['address_id'], ['_id'])
    op.drop_column('order', 'shipping_services')
    op.create_foreign_key(None, 'order_detail', 'product', ['product_item_number'], ['item_number'])
    op.create_foreign_key(None, 'order_detail', 'order', ['order_id'], ['_id'])
    op.create_foreign_key(None, 'payment_information_2_customer', 'customer', ['customer_number'], ['customer_number'])
    op.create_foreign_key(None, 'payment_information_2_customer', 'payment_information', ['payment_information_id'],
                          ['_id'])
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['_id'])
    op.create_foreign_key(None, 'product', 'supplier', ['supplier_id'], ['_id'])
    op.create_foreign_key(None, 'product_2_warehouse', 'warehouse', ['warehouse_id'], ['_id'])
    op.create_foreign_key(None, 'product_2_warehouse', 'product', ['product_item_number'], ['item_number'])
    op.create_foreign_key(None, 'shipping_service', 'address', ['address_id'], ['_id'])
    op.create_foreign_key(None, 'supplier', 'address', ['address_id'], ['_id'])
    op.create_foreign_key(None, 'warehouse', 'address', ['address_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_constraint(None, 'shipping_service', type_='foreignkey')
    op.drop_constraint(None, 'product_2_warehouse', type_='foreignkey')
    op.drop_constraint(None, 'product_2_warehouse', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'payment_information_2_customer', type_='foreignkey')
    op.drop_constraint(None, 'payment_information_2_customer', type_='foreignkey')
    op.drop_constraint(None, 'order_detail', type_='foreignkey')
    op.drop_constraint(None, 'order_detail', type_='foreignkey')
    op.add_column('order', sa.Column('shipping_services', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_shipping_service_id'), table_name='order')
    op.create_index('ix_order_shipping_services', 'order', ['shipping_services'], unique=False)
    op.drop_column('order', 'shipping_service_id')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'address_2_customer', type_='foreignkey')
    op.drop_constraint(None, 'address_2_customer', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
