"""added user table

Revision ID: 217119fee708
Revises: 99cccb38ce41
Create Date: 2022-04-28 13:23:26.730009

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '217119fee708'
down_revision = '99cccb38ce41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user', sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False), sa.PrimaryKeyConstraint('_id'))
    op.create_index(op.f('ix_user__id'), 'user', ['_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user__id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
