"""added token version to user

Revision ID: 73bfa6963535
Revises: 217119fee708
Create Date: 2022-06-04 18:11:54.897989

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '73bfa6963535'
down_revision = '217119fee708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_version', sa.Integer(), nullable=True))
    op.drop_index('ix_user__id', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('ix_user__id', 'user', ['id'], unique=False)
    op.drop_column('user', 'token_version')
    # ### end Alembic commands ###
