"""create tables

Revision ID: b398073187b3
Revises: 
Create Date: 2022-04-04 11:34:28.940558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b398073187b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address2customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'address_id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_country'), 'addresses', ['country'], unique=False)
    op.create_index(op.f('ix_addresses_house_number'), 'addresses', ['house_number'], unique=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_postal_code'), 'addresses', ['postal_code'], unique=False)
    op.create_index(op.f('ix_addresses_region'), 'addresses', ['region'], unique=False)
    op.create_index(op.f('ix_addresses_street'), 'addresses', ['street'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_description'), 'categories', ['description'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('manager', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_manager'), 'departments', ['manager'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('employees',
    sa.Column('employee_number', sa.Integer(), nullable=False),
    sa.Column('ssn', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('employee_number')
    )
    op.create_index(op.f('ix_employees_address_id'), 'employees', ['address_id'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=False)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_job_title'), 'employees', ['job_title'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_phone_number'), 'employees', ['phone_number'], unique=False)
    op.create_index(op.f('ix_employees_ssn'), 'employees', ['ssn'], unique=True)
    op.create_index(op.f('ix_employees_title'), 'employees', ['title'], unique=False)
    op.create_index(op.f('ix_employees_warehouse_id'), 'employees', ['warehouse_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'OVERDUE', 'PAID', name='invoicestatus'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_information_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_issue_date'), 'invoices', ['issue_date'], unique=False)
    op.create_index(op.f('ix_invoices_payment_information_id'), 'invoices', ['payment_information_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('orderdetails',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_item_number', sa.Integer(), nullable=False),
    sa.Column('price_at_time_of_purchase', sa.Float(), nullable=True),
    sa.Column('number_of_items', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('order_id', 'product_item_number')
    )
    op.create_index(op.f('ix_orderdetails_number_of_items'), 'orderdetails', ['number_of_items'], unique=False)
    op.create_index(op.f('ix_orderdetails_order_id'), 'orderdetails', ['order_id'], unique=False)
    op.create_index(op.f('ix_orderdetails_price_at_time_of_purchase'), 'orderdetails', ['price_at_time_of_purchase'], unique=False)
    op.create_index(op.f('ix_orderdetails_product_item_number'), 'orderdetails', ['product_item_number'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'SENT', 'DELIVERED', name='orderstatus'), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('shipping_services', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_address_id'), 'orders', ['address_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_employee_id'), 'orders', ['employee_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_invoice_id'), 'orders', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_orders_shipping_services'), 'orders', ['shipping_services'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('paymentinformation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentinformation_bic'), 'paymentinformation', ['bic'], unique=False)
    op.create_index(op.f('ix_paymentinformation_iban'), 'paymentinformation', ['iban'], unique=True)
    op.create_index(op.f('ix_paymentinformation_id'), 'paymentinformation', ['id'], unique=False)
    op.create_table('paymentinformation2customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('payment_information_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id', 'payment_information_id')
    )
    op.create_index(op.f('ix_paymentinformation2customer_customer_id'), 'paymentinformation2customer', ['customer_id'], unique=False)
    op.create_index(op.f('ix_paymentinformation2customer_payment_information_id'), 'paymentinformation2customer', ['payment_information_id'], unique=False)
    op.create_table('postalcode2city',
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('postal_code')
    )
    op.create_index(op.f('ix_postalcode2city_city'), 'postalcode2city', ['city'], unique=False)
    op.create_index(op.f('ix_postalcode2city_postal_code'), 'postalcode2city', ['postal_code'], unique=False)
    op.create_table('product2warehouse',
    sa.Column('product_item_number', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('number_in_stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_item_number', 'warehouse_id')
    )
    op.create_index(op.f('ix_product2warehouse_number_in_stock'), 'product2warehouse', ['number_in_stock'], unique=False)
    op.create_index(op.f('ix_product2warehouse_product_item_number'), 'product2warehouse', ['product_item_number'], unique=False)
    op.create_index(op.f('ix_product2warehouse_warehouse_id'), 'product2warehouse', ['warehouse_id'], unique=False)
    op.create_table('products',
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_number')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_item_number'), 'products', ['item_number'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_table('shippingservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippingservices_address_id'), 'shippingservices', ['address_id'], unique=False)
    op.create_index(op.f('ix_shippingservices_email'), 'shippingservices', ['email'], unique=False)
    op.create_index(op.f('ix_shippingservices_id'), 'shippingservices', ['id'], unique=False)
    op.create_index(op.f('ix_shippingservices_name'), 'shippingservices', ['name'], unique=False)
    op.create_index(op.f('ix_shippingservices_phone_number'), 'shippingservices', ['phone_number'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_address_id'), 'suppliers', ['address_id'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_phone_number'), 'suppliers', ['phone_number'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_address_id'), 'warehouses', ['address_id'], unique=False)
    op.create_index(op.f('ix_warehouses_email'), 'warehouses', ['email'], unique=False)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_phone_number'), 'warehouses', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_phone_number'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_email'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_address_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_suppliers_phone_number'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_address_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_shippingservices_phone_number'), table_name='shippingservices')
    op.drop_index(op.f('ix_shippingservices_name'), table_name='shippingservices')
    op.drop_index(op.f('ix_shippingservices_id'), table_name='shippingservices')
    op.drop_index(op.f('ix_shippingservices_email'), table_name='shippingservices')
    op.drop_index(op.f('ix_shippingservices_address_id'), table_name='shippingservices')
    op.drop_table('shippingservices')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_item_number'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product2warehouse_warehouse_id'), table_name='product2warehouse')
    op.drop_index(op.f('ix_product2warehouse_product_item_number'), table_name='product2warehouse')
    op.drop_index(op.f('ix_product2warehouse_number_in_stock'), table_name='product2warehouse')
    op.drop_table('product2warehouse')
    op.drop_index(op.f('ix_postalcode2city_postal_code'), table_name='postalcode2city')
    op.drop_index(op.f('ix_postalcode2city_city'), table_name='postalcode2city')
    op.drop_table('postalcode2city')
    op.drop_index(op.f('ix_paymentinformation2customer_payment_information_id'), table_name='paymentinformation2customer')
    op.drop_index(op.f('ix_paymentinformation2customer_customer_id'), table_name='paymentinformation2customer')
    op.drop_table('paymentinformation2customer')
    op.drop_index(op.f('ix_paymentinformation_id'), table_name='paymentinformation')
    op.drop_index(op.f('ix_paymentinformation_iban'), table_name='paymentinformation')
    op.drop_index(op.f('ix_paymentinformation_bic'), table_name='paymentinformation')
    op.drop_table('paymentinformation')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_services'), table_name='orders')
    op.drop_index(op.f('ix_orders_invoice_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_employee_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_address_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_orderdetails_product_item_number'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_price_at_time_of_purchase'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_order_id'), table_name='orderdetails')
    op.drop_index(op.f('ix_orderdetails_number_of_items'), table_name='orderdetails')
    op.drop_table('orderdetails')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_information_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issue_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_employees_warehouse_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_title'), table_name='employees')
    op.drop_index(op.f('ix_employees_ssn'), table_name='employees')
    op.drop_index(op.f('ix_employees_phone_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_job_title'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_address_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_manager'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_description'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_addresses_street'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_region'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_postal_code'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_house_number'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_country'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('address2customer')
    # ### end Alembic commands ###
