"""renamed id to avoid overwriting built-in function

Revision ID: ce37814209a6
Revises: b398073187b3
Create Date: 2022-04-10 10:06:46.045245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce37814209a6'
down_revision = 'b398073187b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address2customer', sa.Column('customer_number', sa.Integer(), nullable=False))
    op.drop_column('address2customer', 'customer_id')
    op.add_column('addresses', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_addresses_id', table_name='addresses')
    op.create_index(op.f('ix_addresses__id'), 'addresses', ['_id'], unique=False)
    op.drop_column('addresses', 'id')
    op.add_column('categories', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_categories_id', table_name='categories')
    op.create_index(op.f('ix_categories__id'), 'categories', ['_id'], unique=False)
    op.drop_column('categories', 'id')
    op.add_column('departments', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_departments_id', table_name='departments')
    op.create_index(op.f('ix_departments__id'), 'departments', ['_id'], unique=False)
    op.drop_column('departments', 'id')
    op.add_column('invoices', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_invoices_id', table_name='invoices')
    op.create_index(op.f('ix_invoices__id'), 'invoices', ['_id'], unique=False)
    op.drop_column('invoices', 'id')
    op.add_column('orders', sa.Column('_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('customer_number', sa.Integer(), nullable=True))
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_index('ix_orders_id', table_name='orders')
    op.create_index(op.f('ix_orders__id'), 'orders', ['_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_number'), 'orders', ['customer_number'], unique=False)
    op.drop_column('orders', 'id')
    op.drop_column('orders', 'customer_id')
    op.add_column('paymentinformation', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_paymentinformation_id', table_name='paymentinformation')
    op.create_index(op.f('ix_paymentinformation__id'), 'paymentinformation', ['_id'], unique=False)
    op.drop_column('paymentinformation', 'id')
    op.add_column('paymentinformation2customer', sa.Column('customer_number', sa.Integer(), nullable=False))
    op.drop_index('ix_paymentinformation2customer_customer_id', table_name='paymentinformation2customer')
    op.create_index(op.f('ix_paymentinformation2customer_customer_number'), 'paymentinformation2customer', ['customer_number'], unique=False)
    op.drop_column('paymentinformation2customer', 'customer_id')
    op.add_column('shippingservices', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_shippingservices_id', table_name='shippingservices')
    op.create_index(op.f('ix_shippingservices__id'), 'shippingservices', ['_id'], unique=False)
    op.drop_column('shippingservices', 'id')
    op.add_column('suppliers', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_suppliers_id', table_name='suppliers')
    op.create_index(op.f('ix_suppliers__id'), 'suppliers', ['_id'], unique=False)
    op.drop_column('suppliers', 'id')
    op.add_column('warehouses', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_index('ix_warehouses_id', table_name='warehouses')
    op.create_index(op.f('ix_warehouses__id'), 'warehouses', ['_id'], unique=False)
    op.drop_column('warehouses', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_warehouses__id'), table_name='warehouses')
    op.create_index('ix_warehouses_id', 'warehouses', ['id'], unique=False)
    op.drop_column('warehouses', '_id')
    op.add_column('suppliers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_suppliers__id'), table_name='suppliers')
    op.create_index('ix_suppliers_id', 'suppliers', ['id'], unique=False)
    op.drop_column('suppliers', '_id')
    op.add_column('shippingservices', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_shippingservices__id'), table_name='shippingservices')
    op.create_index('ix_shippingservices_id', 'shippingservices', ['id'], unique=False)
    op.drop_column('shippingservices', '_id')
    op.add_column('paymentinformation2customer', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_paymentinformation2customer_customer_number'), table_name='paymentinformation2customer')
    op.create_index('ix_paymentinformation2customer_customer_id', 'paymentinformation2customer', ['customer_id'], unique=False)
    op.drop_column('paymentinformation2customer', 'customer_number')
    op.add_column('paymentinformation', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_paymentinformation__id'), table_name='paymentinformation')
    op.create_index('ix_paymentinformation_id', 'paymentinformation', ['id'], unique=False)
    op.drop_column('paymentinformation', '_id')
    op.add_column('orders', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_orders_customer_number'), table_name='orders')
    op.drop_index(op.f('ix_orders__id'), table_name='orders')
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.drop_column('orders', 'customer_number')
    op.drop_column('orders', '_id')
    op.add_column('invoices', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_invoices__id'), table_name='invoices')
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.drop_column('invoices', '_id')
    op.add_column('departments', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_departments__id'), table_name='departments')
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.drop_column('departments', '_id')
    op.add_column('categories', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_categories__id'), table_name='categories')
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.drop_column('categories', '_id')
    op.add_column('addresses', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_addresses__id'), table_name='addresses')
    op.create_index('ix_addresses_id', 'addresses', ['id'], unique=False)
    op.drop_column('addresses', '_id')
    op.add_column('address2customer', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('address2customer', 'customer_number')
    # ### end Alembic commands ###
